// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"
	ent "service-catalog/ent"

	mock "github.com/stretchr/testify/mock"

	service "service-catalog/service"
)

// ServiceRepoInterface is an autogenerated mock type for the ServiceRepoInterface type
type ServiceRepoInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, attributes
func (_m *ServiceRepoInterface) Create(c context.Context, attributes service.ServiceRequest) (*ent.Service, error) {
	ret := _m.Called(c, attributes)

	var r0 *ent.Service
	if rf, ok := ret.Get(0).(func(context.Context, service.ServiceRequest) *ent.Service); ok {
		r0 = rf(c, attributes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Service)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, service.ServiceRequest) error); ok {
		r1 = rf(c, attributes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateVersion provides a mock function with given fields: c, serviceID, r
func (_m *ServiceRepoInterface) CreateVersion(c context.Context, serviceID int, r service.VersionRequest) (*ent.Service, error) {
	ret := _m.Called(c, serviceID, r)

	var r0 *ent.Service
	if rf, ok := ret.Get(0).(func(context.Context, int, service.VersionRequest) *ent.Service); ok {
		r0 = rf(c, serviceID, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Service)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, service.VersionRequest) error); ok {
		r1 = rf(c, serviceID, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: c, serviceID
func (_m *ServiceRepoInterface) Delete(c context.Context, serviceID int) error {
	ret := _m.Called(c, serviceID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(c, serviceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, searchBy, sortBy, pageOffset, itemsPerPage
func (_m *ServiceRepoInterface) Get(ctx context.Context, searchBy string, sortBy string, pageOffset int, itemsPerPage int) ([]*ent.Service, error) {
	ret := _m.Called(ctx, searchBy, sortBy, pageOffset, itemsPerPage)

	var r0 []*ent.Service
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*ent.Service); ok {
		r0 = rf(ctx, searchBy, sortBy, pageOffset, itemsPerPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.Service)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, searchBy, sortBy, pageOffset, itemsPerPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: c, id
func (_m *ServiceRepoInterface) GetByID(c context.Context, id int) (*ent.Service, error) {
	ret := _m.Called(c, id)

	var r0 *ent.Service
	if rf, ok := ret.Get(0).(func(context.Context, int) *ent.Service); ok {
		r0 = rf(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Service)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVersions provides a mock function with given fields: c, serviceID
func (_m *ServiceRepoInterface) GetVersions(c context.Context, serviceID int) ([]*ent.Version, error) {
	ret := _m.Called(c, serviceID)

	var r0 []*ent.Version
	if rf, ok := ret.Get(0).(func(context.Context, int) []*ent.Version); ok {
		r0 = rf(c, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.Version)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(c, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, serviceID, r
func (_m *ServiceRepoInterface) Update(c context.Context, serviceID int, r service.ServiceRequest) (*ent.Service, error) {
	ret := _m.Called(c, serviceID, r)

	var r0 *ent.Service
	if rf, ok := ret.Get(0).(func(context.Context, int, service.ServiceRequest) *ent.Service); ok {
		r0 = rf(c, serviceID, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Service)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, service.ServiceRequest) error); ok {
		r1 = rf(c, serviceID, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewServiceRepoInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceRepoInterface creates a new instance of ServiceRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceRepoInterface(t mockConstructorTestingTNewServiceRepoInterface) *ServiceRepoInterface {
	mock := &ServiceRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
